site_name: Elsie

site_url: https://spirali.github.io/elsie/
repo_url: https://github.com/spirali/elsie
edit_uri: blob/master/docs/

site_description: Documentation of the elsie Python library.
site_author: Stanislav BÃ¶hm

google_analytics: ['G-V9H5Q6FZ6D', 'https://spirali.github.io/elsie/']

nav:
  - Overview: README.md
  - installation.md
  - getting_started.md
  - gallery.md
  - User guide:
    - userguide/basics.md
    - userguide/layout.md
    - userguide/revealing.md
    - userguide/text.md
    - userguide/syntax_highlighting.md
    - userguide/images.md
    - userguide/shapes.md
    - userguide/lists.md
    - userguide/jupyter.md
    - userguide/latex.md
  - Cookbook:
    - cookbook/grids.md
    - cookbook/codestepping.md
    - cookbook/zoom.md
    - cookbook/postprocessing.md
  - API reference:
    - API documentation: apidoc

theme: readthedocs

markdown_extensions:
  - toc:
      permalink: "#"

plugins:
  - elsie
  - nedoc
